'use strict';

// Pure validation helpers are kept dependency-free for GitHub Actions.
const SAFE_BRANCH = /^(?!\/)(?!.*(?:\.\.|@\{|\/\/))[A-Za-z0-9._/-]+(?<!\/)$/;
const TRUSTED_ASSOCIATIONS = new Set(['OWNER', 'MEMBER', 'COLLABORATOR']);
const REQUIRED_HEADINGS = {
  Bug: [
    'Target branch',
    'Problem summary',
    'Current behavior',
    'Expected behavior',
    'Steps to reproduce',
    'Acceptance criteria',
    'Validation and evidence',
    'Safety check'
  ],
  Feature: [
    'Target branch',
    'Problem and context',
    'Desired behavior',
    'Acceptance criteria',
    'Validation and evidence',
    'Safety check'
  ],
  Task: [
    'Target branch',
    'Context',
    'Required change',
    'Acceptance criteria',
    'Validation and evidence',
    'Safety check'
  ]
};

// Accept the heading generated by a GitHub Issue Form and a documented inline
// fallback while rejecting values that are unsafe to pass to Git or the API.
function extractTargetBranch(body) {
  const text = body || '';
  const headingMatch = text.match(
    /^#{2,6}\s+Target branch\s*\r?\n+(?:<!--[\s\S]*?-->\s*)*`?([^\s`]+)`?\s*$/im
  );
  const inlineMatch = text.match(
    /^(?:[-*]\s*)?(?:\*\*)?Target branch(?:\*\*)?\s*:\s*`?([^\s`]+)`?\s*$/im
  );
  const branch = (headingMatch?.[1] || inlineMatch?.[1] || '').trim();

  if (
    !branch ||
    !SAFE_BRANCH.test(branch) ||
    branch.endsWith('.') ||
    branch.endsWith('.lock')
  ) {
    return null;
  }

  return branch;
}

// GitHub author association is more reliable than maintaining a username list.
function isTrustedAssociation(association) {
  return TRUSTED_ASSOCIATIONS.has(association);
}

// Labels are useful review metadata but are not the automation trigger. The
// workflow provisions and applies them after the target-branch field starts it.
function automationLabelsForIssue(issue) {
  const title = (issue.title || '').trim();
  const labels = ['codex-fix-requested'];

  if (/^\[Bug\]:/i.test(title)) {
    labels.push('bug', 'needs reproduction');
  } else if (/^\[Feature\]:/i.test(title)) {
    labels.push('feature');
  } else if (/^\[Task\]:/i.test(title)) {
    labels.push('technical task');
  }

  return labels;
}

// Issue Forms enforce detailed fields in the UI; these checks protect API-made
// or manually edited issues from starting an underspecified agent run.
function validateIssue(issue) {
  const problems = [];
  const title = (issue.title || '').trim();
  const body = (issue.body || '').trim();

  if (title.length < 10) {
    problems.push('Use a descriptive issue title of at least 10 characters.');
  }
  if (body.length < 80) {
    problems.push(
      'Provide enough context, expected behavior, acceptance criteria, and validation details.'
    );
  }

  const typeMatch = title.match(/^\[(Bug|Feature|Task)\]:\s+\S/i);
  if (!typeMatch) {
    problems.push('Use the Bug, Feature, or Technical Task issue form and title prefix.');
    return { problems };
  }

  const issueType = typeMatch[1][0].toUpperCase() + typeMatch[1].slice(1).toLowerCase();
  for (const heading of REQUIRED_HEADINGS[issueType]) {
    const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const section = body.match(
      new RegExp(
        `^#{2,6}\\s+${escaped}\\s*$([\\s\\S]*?)(?=^#{2,6}\\s+|(?![\\s\\S]))`,
        'im'
      )
    );
    const value = (section?.[1] || '').trim();
    if (!value || value === '_No response_') {
      problems.push(`Complete the required \`${heading}\` section.`);
    }
  }

  if (!/^- \[[xX]\] I removed secrets, credentials, tokens, and sensitive personal data from this issue\.\s*$/m.test(body)) {
    problems.push('Confirm the required Safety check checkbox.');
  }

  return { problems };
}

// Export only deterministic helpers; GitHub API operations stay in the workflow.
module.exports = {
  automationLabelsForIssue,
  extractTargetBranch,
  isTrustedAssociation,
  validateIssue
};
